Replace deprecated react hls player
twelvelabs-io/tl-jockey pull request #105
Opened 2024-11-12 18:47 UTC by seyeong-han

### Parent Issue
[2. react-hls-player dependency conflict issue with react@18.0.0](#68)  

I got the [react-hls-player](https://github.com/devcshort/react-hls) dependency conflict issue and found it has been stopped from being maintained since 2021.

## Fix
- Replaced the `react-hls-player` with `react-player@2.16.0`.
- Fixed `useVideoElementEffectProps` types for react-player

## Result
![image](https://github.com/user-attachments/assets/b97b603c-4c96-4da4-afab-4743245d5187)

2024-11-20 21:51 UTC, DmitriiTsy commented
Good idea @seyeong-han  Switching to react-player is definitely the way to go since it gives us out of the box support for different & multiple media sources like YouTube, Vimeo, and etc , which is perfect for scaling up . Plus, with its built-in controls and playback events, we’ll have more flexibility and control do develop better features in the future.  


I think overall changes is looks good, thank you for contributing @seyeong-han appreciate it 

I have a couple important things to mention. We were using "poster" as a way to show a thumbnail of the video while videos is loading (instead of a black screen or smith like this) I know that in this current library we have a specific tool to do the same called "light" 

The other thing is this thumbnail  (poster/light) is relying a lot on the dimensions and they should be strict like 850px for width and 560px for height (we can use our previous ones as well )

2024-11-21 19:08 UTC, DmitriiTsy requested changes

2024-11-30 23:25 UTC, seyeong-han commented on frontend/src/components/Modal/ModalCentral.tsx
> -              poster={fallbackImage}
I fixed it in my new commit!

2024-11-30 23:28 UTC, seyeong-han commented on frontend/src/components/Modal/ModalCentral.tsx
> +              width="100%"
If I set the width to 850px and the height to 560px, the modal does not align properly with the video's dimensions. Even though it doesn't fit, I followed your suggested size adjustments.

![image](https://github.com/user-attachments/assets/b14ad01c-50f2-45b1-a5cf-d85fd921693d)

2024-11-30 23:29 UTC, seyeong-han commented on frontend/src/components/Modal/ModalCentral.tsx
> +              width="100%"
@DmitriiTsy I’ve updated the code based on your suggestions!

2024-12-16 20:00 UTC, DmitriiTsy commented
Since the last time we checked this PR, we have implemented a lot of UI changes that may affect some of the changes in this PR. Therefore, this PR can be closed for now @seyeong-han

2024-12-16 20:00 UTC, closed without merging