[Feature/frontend] add `.env` instructions for frontend
twelvelabs-io/tl-jockey pull request #70
Opened 2024-08-27 01:13 UTC by seyeong-han

The parent issue was [Errors while onboarding frontend app #68](https://github.com/twelvelabs-io/tl-jockey/issues/68).

## Updates
- Add [frontend/example.env](frontend/example.env) and instructions for it on `README.md`
- Add `@langchain/langgraph-sdk` required package
- Add `dotenv` required in `frontend/server.js`
- Unified `.env` variables for `frontend/server.js` and frontend's `frontend/src/apis/apiConfig.js`

2024-09-03 21:05 UTC, DmitriiTsy requested changes
Just a couple of things left => once they're ready, we can approve and merge

2024-09-03 21:05 UTC, DmitriiTsy commented on frontend/src/apis/streamEventsApis.js
I double-checked the official documentation regarding SDK and user examples. It seems that we can only work with an apiURL here, without any need for apiKeys or similar configurations. @seyeong-han

2024-09-05 15:25 UTC, seyeong-han commented on frontend/src/apis/streamEventsApis.js
Yes, you are right.
I checked the `new Client` without `apiKey` and it could communicate with `jockey server`.
Let me fix this line.

2024-09-05 15:25 UTC, seyeong-han commented on frontend/src/apis/streamEventsApis.js
Yes, you are right.
I checked the `new Client` without `apiKey` and it could communicate with `jockey server`.
Let me fix this line.

2024-10-02 19:20 UTC, james-le-twelve-labs approved these changes
@DmitriiTsy Thanks for reviewing!

2024-10-02 19:21 UTC, merged